# Config file for air in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Binary file yielded from go build.
bin = "./tmp/main"
# Command to build the project.
cmd = "go build -o ./tmp/main ./cmd/api"
# This log name is only available for default logger
log = "air.log"
# Just plain old shell command
full_bin = "./tmp/main"
# Watch these directories for changes
include_ext = ["go", "tpl", "tmpl", "html", "env"]
include_dir = ["cmd", "internal", "pkg", "proto"]
# Exclude these directories from watching
exclude_dir = ["tmp", "vendor"]
# Watch these files for changes
include_file = []
# Exclude these files from watching
exclude_file = []
# Exclude unchanged files
exclude_unchanged = true
# Follow symlink for directories
follow_symlink = true
# Delay after each execution
delay = 1000 # ms
# Send interrupt signal before killing process (windows does not support this feature)
send_interrupt = true
# Kill process if it's still running after this duration
kill_delay = 500 # ms
# Rerun on error
rerun = true
# Delay after each rerun
rerun_delay = 500

[log]
# Show log timestamp
time = true

[color]
# Custom colors
main = "magenta"
build = "cyan"
runner = "green"
watcher = "yellow"

[misc]
# Clean tmp dir on exit
clean_on_exit = true